package client.controllers;

import client.LinkedScene;
import client.controllers.questions.QuestionInsertNumberCtrl;
import client.controllers.questions.QuestionMultiOptionsCtrl;
import client.controllers.questions.QuestionSameAsCtrl;
import client.utils.ServerUtils;
import com.google.inject.Inject;
import commons.JokersList;
import commons.Player;
import commons.Question;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javafx.util.Pair;

import java.util.Arrays;
import java.util.List;

public class MainAppController {
    private final ServerUtils serverUtils;
    private Scene waitingRoomScene;
    private Stage primaryStage;
    private Scene homeScene;
    private Scene leaderBoardScene;
    private Scene qMultiScene;
    private Scene qInsert;
    private Scene questionTransitionScene;
    private Scene sameAsScene;
    private Scene homeSingleplayerScene;
    private Scene homeMultiplayerScene;

    private LinkedScene currentScene;
    private LinkedScene homeScreenLinked;

    private String name;

    private QuestionInsertNumberCtrl qInsertCtrl;
    private QuestionMultiOptionsCtrl qMultiCtrl;
    private TransitionSceneCtrl qTransitionCtrl;

    private int gameID; // Game ID that the client stores and is sent to get the question

    private List<Question> questionsInGame;
    private int questionIndex = 0;
    private JokersList jokers;

    @Inject
    MainAppController(ServerUtils serverUtils) {
        this.serverUtils = serverUtils;
    }

    public void initialize(Stage primaryStage, Pair<WaitingRoomCtrl, Parent> waitingRoomPair,
                           Pair<HomeScreenCtrl, Parent> home,
                           Pair<HomeScreenSingleplayerCtrl, Parent> homeSingleplayer,
                           Pair<HomeScreenMultiplayerCtrl, Parent> homeMultiplayer,
                           Pair<LeaderBoardCtrl, Parent> leaderBoard,
                           Pair<QuestionMultiOptionsCtrl, Parent> qMulti,
                           Pair<QuestionInsertNumberCtrl, Parent> qInsert,
                           Pair<QuestionSameAsCtrl, Parent> sameAs,
                           Pair<TransitionSceneCtrl, Parent> qTransition) {

        this.name = "";
        this.waitingRoomScene = new Scene(waitingRoomPair.getValue());
        this.homeScene = new Scene(home.getValue());
        this.homeSingleplayerScene = new Scene(homeSingleplayer.getValue());
        this.homeMultiplayerScene = new Scene(homeMultiplayer.getValue());
        this.leaderBoardScene = new Scene(leaderBoard.getValue());

        this.questionTransitionScene = new Scene(qTransition.getValue());
        this.qTransitionCtrl = qTransition.getKey();

        this.sameAsScene = new Scene(sameAs.getValue());

        LinkedScene waitingRoomLinked = new LinkedScene(this.waitingRoomScene);
        LinkedScene leaderBoardLinked = new LinkedScene(this.leaderBoardScene);
        LinkedScene sameAsLinked = new LinkedScene(this.sameAsScene);
        LinkedScene singleplayerLinked = new LinkedScene(this.homeSingleplayerScene, homeSingleplayer.getKey());
        LinkedScene multiplayerLinked = new LinkedScene(this.homeMultiplayerScene, homeMultiplayer.getKey());

        // replace leaderBoardLinked by the waiting screen, whose controller can load the questions
        this.currentScene = new LinkedScene(this.homeScene,
                Arrays.asList(singleplayerLinked, multiplayerLinked));
        this.homeScreenLinked = this.currentScene;

        multiplayerLinked.addNext(waitingRoomLinked);

        this.primaryStage = primaryStage;

        this.qInsertCtrl = qInsert.getKey();
        this.qInsert = new Scene(qInsert.getValue());
        this.qMultiCtrl = qMulti.getKey();
        this.qMultiScene = new Scene(qMulti.getValue());
        jokers = new JokersList();

        primaryStage.setScene(homeScene);
        primaryStage.show();

        this.homeScene.getStylesheets().add("client/scenes/waiting_room.css");
        this.qMultiScene.getStylesheets().add("client/scenes/waiting_room.css");
        this.waitingRoomScene.getStylesheets().add("client/scenes/waiting_room.css");
        this.sameAsScene.getStylesheets().add("client/scenes/waiting_room.css");
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public JokersList getJokers() {
        return this.jokers;
    }

    public void setGameID(int gameID) {
        this.gameID = gameID;
        System.out.println(gameID);
    }

    public int getGameID() {
        return this.gameID;
    }

    public int getQuestionIndex() {
        return questionIndex;
    }

    /**
     * This method takes a list of actual question  and inserts
     * them into the LinkedScene navigation.
     *
     * @param questions List of questions objects, generated by the server
     * @param mode      either 0 or 1. 0 indicates single player mode, 1 multiplayer.
     **/
    public void addQuestionScenes(List<Question> questions, int mode) {
        LinkedScene current = this.currentScene;
        questionsInGame = questions;
        for (int i = 0; i < questions.size(); i++) {
            if (i == 10) {
                current.addNext(new LinkedScene(this.leaderBoardScene));
                current = current.getNext();
            } else {
                // add the transition before a normal question
                current.addNext(new LinkedScene(this.questionTransitionScene, this.qTransitionCtrl));
                current = current.getNext();
            }
//            if(questionTypes.get(i) < 2) {
//                current.addNext(new LinkedScene(this.qMultiScene, this.qMultiCtrl));
//            } else {
//                current.addNext(new LinkedScene(this.qInsert, this.qInsertCtrl));
//            }
            current.addNext(new LinkedScene(this.qMultiScene, this.qMultiCtrl));
            current = current.getNext();
        }
        current.addNext(new LinkedScene(this.leaderBoardScene,
                Arrays.asList(homeScreenLinked, homeScreenLinked.getNext(mode))));
    }

    /*
     * This method shows the next scene in the list of linked scenes
     */
    public void showNext() {
        this.currentScene = this.currentScene.getNext();

        primaryStage.setScene(this.currentScene.getScene());
        if (this.currentScene.getTitle() != null) {
            primaryStage.setTitle(this.currentScene.getTitle());
        }
        primaryStage.show();
        Object controller = this.currentScene.getController();
        // if this controller is of the question then set the question
        if (controller instanceof QuestionMultiOptionsCtrl qController) {
            qController.setQuestion(questionsInGame.get(questionIndex));
            questionIndex++;
        }
        // if this controller is of the question then set the question
        else if (controller instanceof QuestionInsertNumberCtrl qController) {
            qController.setQuestion(questionsInGame.get(questionIndex));
            questionIndex++;
        }
        if (controller instanceof ControllerInitialize controllerInit) {
            controllerInit.initializeController();
        }

    }

    /*
     * @param i in case multiple scenes follow the current scene,
     * the index of the following scenes is used to specify which
     * one to show next.
     */
    public void showNext(int i) {
        this.currentScene = this.currentScene.getNext(i);
        primaryStage.setScene(this.currentScene.getScene());
        if (this.currentScene.getTitle() != null) {
            primaryStage.setTitle(this.currentScene.getTitle());
        }
        primaryStage.setOnCloseRequest(event -> this.serverUtils.sendThroughSocket("/app/disconnect", new Player(this.name)));
    }

//    public void showQuestion(Question question) {
//        if(question.getType() == QuestionType.Estimate){
//            showQuestionInsert(question);
//        }else{
//            showQuestionMulti(question);
//        }
//    }
//
//    public void showQuestionInsert(Question q) {
//        qInsertCtrl.setQuestion(q);
//        primaryStage.setTitle("Insert Number question");
//        primaryStage.setScene(qInsert);
//        primaryStage.show();
//    }
//    public void showQuestionMulti(Question q) {
//        qMultiCtrl.setQuestion(q);
//        primaryStage.setTitle("Multiple choice question");
//        primaryStage.setScene(qMultiScene);
//        primaryStage.show();
//        qMultiCtrl.resizeImages();
//        qMultiCtrl.startTimerAnimation();
//    }

    /*
     * Almost every scene has a button to return to the homescreen.
     * That button activates this function. Which switches from the
     * current scene to the homescreen.
     */
    public void showHomeScreen() {
        primaryStage.setTitle("Home");
        primaryStage.setScene(homeScene);
        primaryStage.show();
        this.currentScene = this.homeScreenLinked;
    }

}
